include(`moving_average.m4')dnl
include(`code_generator.m4')dnl

#include "moving_average.h"
#include "assertions.h"

M4_MAKE_FOR_NUMERIC_TYPES(`M4_MAKE_MOVING_AVERAGE_MAKE')

M4_MAKE_FOR_NUMERIC_TYPES(`M4_MAKE_MOVING_AVERAGE_LENGTH')

M4_MAKE_FOR_NUMERIC_TYPES(`M4_MAKE_MOVING_AVERAGE_EVALUATE')

M4_MAKE_FOR_NUMERIC_TYPES(`M4_MAKE_MOVING_AVERAGE_RESET')

M4_MAKE_FOR_NUMERIC_TYPES(`M4_MAKE_MOVING_AVERAGE_FREE')